#[path = "support/mod.rs"]
mod support;

use support::{Case, ExpectedOutcome, block_on, case, run_cases};

pub fn cases() -> Vec<Case> {
    vec![
        // MATH - Basic Arithmetic
        case(
            "3 + 4",
            Some("math"),
            "simple addition",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "10 - 3",
            Some("math"),
            "simple subtraction",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "6 * 7",
            Some("math"),
            "simple multiplication",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "20 / 4",
            Some("math"),
            "simple division",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "10 % 3",
            Some("math"),
            "modulo",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "3 + 43 + 23",
            Some("math"),
            "multi-term addition",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "100 - 50 + 25",
            Some("math"),
            "mixed add/subtract",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2 * 3 + 4",
            Some("math"),
            "operator precedence mul before add",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2 + 3 * 4",
            Some("math"),
            "operator precedence mul before add v2",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "10 / 2 - 1",
            Some("math"),
            "div then subtract",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0 + 0",
            Some("math"),
            "zero addition",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0 * 100",
            Some("math"),
            "zero multiplication",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "100 / 1",
            Some("math"),
            "division by 1",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "-5 + 3",
            Some("math"),
            "negative number addition",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "-5 * -3",
            Some("math"),
            "negative times negative",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "-10 / 2",
            Some("math"),
            "negative division",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0.1 + 0.2",
            Some("math"),
            "floating point addition",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "1.5 * 2.5",
            Some("math"),
            "floating point multiplication",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "99999 + 1",
            Some("math"),
            "large number addition",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "999999999 * 999999999",
            Some("math"),
            "very large multiplication",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Parentheses
        case(
            "(3 + 4) * 2",
            Some("math"),
            "parentheses override precedence",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "((2 + 3) * (4 - 1))",
            Some("math"),
            "nested parentheses",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "(10)",
            Some("math"),
            "single value in parentheses",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "(2 + 3) * (4 + 5)",
            Some("math"),
            "two grouped expressions",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "((1 + 2) + (3 + 4)) * 2",
            Some("math"),
            "deeply nested parentheses",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Exponentiation
        case(
            "2^10",
            Some("math"),
            "caret exponentiation",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2**10",
            Some("math"),
            "double-star exponentiation",
            ExpectedOutcome::Err,
        ),
        case(
            "3^3",
            Some("math"),
            "cube with caret",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "10^0",
            Some("math"),
            "anything to power 0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2^-1",
            Some("math"),
            "negative exponent",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0^0",
            Some("math"),
            "zero to zero edge case",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2^0.5",
            Some("math"),
            "fractional exponent (sqrt)",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Functions
        case(
            "sqrt(144)",
            Some("math"),
            "square root",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sqrt(2)",
            Some("math"),
            "irrational square root",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sqrt(0)",
            Some("math"),
            "sqrt of zero",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sqrt(1)",
            Some("math"),
            "sqrt of one",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sqrt(6)",
            Some("math"),
            "sqrt of 6",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cbrt(27)",
            Some("math"),
            "cube root",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cbrt(8)",
            Some("math"),
            "cube root of 8",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "abs(-5)",
            Some("math"),
            "absolute value negative",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "abs(5)",
            Some("math"),
            "absolute value positive",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "abs(0)",
            Some("math"),
            "absolute value zero",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "ceil(4.2)",
            Some("math"),
            "ceiling",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "ceil(4.9)",
            Some("math"),
            "ceiling close to next int",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "ceil(-4.2)",
            Some("math"),
            "ceiling negative",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "floor(4.9)",
            Some("math"),
            "floor",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "floor(4.1)",
            Some("math"),
            "floor close to int",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "floor(-4.2)",
            Some("math"),
            "floor negative",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "round(4.5)",
            Some("math"),
            "round half up",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "round(4.4)",
            Some("math"),
            "round down",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "round(4.6)",
            Some("math"),
            "round up",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "log(100)",
            Some("math"),
            "log base 10",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "log2(8)",
            Some("math"),
            "log base 2",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "log10(1000)",
            Some("math"),
            "log base 10 explicit",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "ln(1)",
            Some("math"),
            "natural log of 1",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "ln(e)",
            Some("math"),
            "natural log of e",
            ExpectedOutcome::Ok("math"),
        ),
        case("exp(1)", Some("math"), "e^1", ExpectedOutcome::Ok("math")),
        case("exp(0)", Some("math"), "e^0", ExpectedOutcome::Ok("math")),
        case(
            "sin(0)",
            Some("math"),
            "sin of 0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cos(0)",
            Some("math"),
            "cos of 0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "tan(0)",
            Some("math"),
            "tan of 0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sin(pi)",
            Some("math"),
            "sin of pi",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cos(pi)",
            Some("math"),
            "cos of pi",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "asin(0)",
            Some("math"),
            "arcsin of 0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "acos(1)",
            Some("math"),
            "arccos of 1",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "atan(0)",
            Some("math"),
            "arctan of 0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sinh(0)",
            Some("math"),
            "hyperbolic sin",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cosh(0)",
            Some("math"),
            "hyperbolic cos",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "tanh(0)",
            Some("math"),
            "hyperbolic tan",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "pow(2, 10)",
            Some("math"),
            "pow function",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "pow(3, 3)",
            Some("math"),
            "pow function cube",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "max(1, 5, 3)",
            Some("math"),
            "max of three numbers",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "min(1, 5, 3)",
            Some("math"),
            "min of three numbers",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "max(10, 20)",
            Some("math"),
            "max of two numbers",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "min(-5, 5)",
            Some("math"),
            "min with negative",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Constants
        case(
            "pi",
            Some("math"),
            "pi constant",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "e",
            Some("math"),
            "euler number",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "tau",
            Some("math"),
            "tau constant",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "phi",
            Some("math"),
            "golden ratio",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "pi * 2",
            Some("math"),
            "pi times 2 = tau",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "e^2",
            Some("math"),
            "e squared",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2 * pi * 5",
            Some("math"),
            "circumference formula",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Factorial
        case(
            "5!",
            Some("math"),
            "factorial of 5",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0!",
            Some("math"),
            "factorial of 0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "1!",
            Some("math"),
            "factorial of 1",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "10!",
            Some("math"),
            "factorial of 10",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "3! + 4!",
            Some("math"),
            "sum of factorials",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Percentage
        case(
            "50%",
            Some("math"),
            "percentage as decimal",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "100%",
            Some("math"),
            "100 percent",
            ExpectedOutcome::Ok("math"),
        ),
        case("0%", Some("math"), "0 percent", ExpectedOutcome::Ok("math")),
        case(
            "25% * 200",
            Some("math"),
            "25% of 200",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "200 * 15%",
            Some("math"),
            "15% of 200",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Bitwise
        case(
            "5 & 3",
            Some("math"),
            "bitwise AND",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "5 | 3",
            Some("math"),
            "bitwise OR",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "~5",
            Some("math"),
            "bitwise NOT",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "1 << 3",
            Some("math"),
            "left shift",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "8 >> 2",
            Some("math"),
            "right shift",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Base Literals
        case(
            "0xFF",
            Some("math"),
            "hex literal uppercase",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0xff",
            Some("math"),
            "hex literal lowercase",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0xA",
            Some("math"),
            "hex single digit",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0b1010",
            Some("math"),
            "binary literal",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0b11111111",
            Some("math"),
            "binary 255",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0o77",
            Some("math"),
            "octal literal",
            ExpectedOutcome::Ok("math"),
        ),
        case("0o10", Some("math"), "octal 8", ExpectedOutcome::Ok("math")),
        case(
            "0xFF + 1",
            Some("math"),
            "hex in expression",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "0b1010 + 0o10",
            Some("math"),
            "mixed base expression",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Scientific Notation
        case(
            "1e10",
            Some("math"),
            "scientific notation large",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2.5e-3",
            Some("math"),
            "scientific notation small",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "1e0",
            Some("math"),
            "sci notation 10^0",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "3e2 + 5e1",
            Some("math"),
            "sci notation in expression",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "1.23e4",
            Some("math"),
            "sci notation with decimal",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Complex Expressions
        case(
            "sqrt(3^2 + 4^2)",
            Some("math"),
            "pythagorean theorem",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "(1 + sqrt(5)) / 2",
            Some("math"),
            "golden ratio formula",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2 * pi * sqrt(10 / 9.8)",
            Some("math"),
            "pendulum period",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "log2(1024)",
            Some("math"),
            "log2 of power of 2",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sin(pi/4)",
            Some("math"),
            "sin 45 degrees",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cos(pi/3)",
            Some("math"),
            "cos 60 degrees",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sin(pi/2)",
            Some("math"),
            "sin 90 degrees",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "floor(3.7) + ceil(2.1)",
            Some("math"),
            "combined floor/ceil",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Edge Cases / Errors
        case(
            "1 / 0",
            Some("error"),
            "division by zero",
            ExpectedOutcome::Err,
        ),
        case("", Some("error"), "empty input", ExpectedOutcome::Err),
        case(
            "   ",
            Some("error"),
            "whitespace only",
            ExpectedOutcome::Err,
        ),
        case(
            "hello world",
            Some("error"),
            "random text",
            ExpectedOutcome::Err,
        ),
        case(
            "abc + def",
            Some("error"),
            "non-numeric text in math",
            ExpectedOutcome::Err,
        ),
        case(
            "+++",
            Some("error"),
            "invalid operators",
            ExpectedOutcome::Err,
        ),
        case(
            "(()",
            Some("error"),
            "unbalanced parentheses",
            ExpectedOutcome::Err,
        ),
        case(
            "3 +",
            Some("error"),
            "incomplete expression",
            ExpectedOutcome::Err,
        ),
        case(
            "* 5",
            Some("error"),
            "leading operator",
            ExpectedOutcome::Err,
        ),
        case(
            "infinity",
            Some("math"),
            "infinity constant",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "infinity + 1",
            Some("math"),
            "infinity arithmetic",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "infinity - infinity",
            Some("math"),
            "infinity minus infinity",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sqrt(-1)",
            Some("math"),
            "sqrt of negative (NaN?)",
            ExpectedOutcome::Ok("math"),
        ),
        // MATH - Human Natural Language
        case(
            "square root of 144",
            Some("math"),
            "natural: square root of",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "square root of 6",
            Some("math"),
            "natural: square root of 6",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cube root of 27",
            Some("math"),
            "natural: cube root of",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "what is 5 + 3",
            Some("math"),
            "natural: what is X + Y",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "whats 10 * 5",
            Some("math"),
            "natural: whats X * Y",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "calculate 100 / 4",
            Some("math"),
            "natural: calculate X / Y",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "what is the square root of 16",
            Some("math"),
            "natural: what is the sqrt",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2 to the power of 10",
            Some("math"),
            "natural: X to the power of Y",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "5 squared",
            Some("math"),
            "natural: X squared",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "3 cubed",
            Some("math"),
            "natural: X cubed",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "10 percent of 200",
            Some("math"),
            "natural: X percent of Y",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "20% of 500",
            Some("math"),
            "natural: X% of Y",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "half of 100",
            Some("math"),
            "natural: half of X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "double 50",
            Some("math"),
            "natural: double X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "triple 33",
            Some("math"),
            "natural: triple X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "one third of 99",
            Some("math"),
            "natural: one third of X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "one quarter of 100",
            Some("math"),
            "natural: one quarter of X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "log of 100",
            Some("math"),
            "natural: log of X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "sine of 0",
            Some("math"),
            "natural: sine of X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "cosine of 0",
            Some("math"),
            "natural: cosine of X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "tangent of 0",
            Some("math"),
            "natural: tangent of X",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "absolute value of -5",
            Some("math"),
            "natural: absolute value of",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "factorial of 5",
            Some("math"),
            "natural: factorial of",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2 plus 3",
            Some("math"),
            "natural: word operators plus",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "10 minus 3",
            Some("math"),
            "natural: word operators minus",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "6 times 7",
            Some("math"),
            "natural: word operators times",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "20 divided by 4",
            Some("math"),
            "natural: word operators divided by",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "2 raised to 10",
            Some("math"),
            "natural: raised to",
            ExpectedOutcome::Ok("math"),
        ),
        case(
            "remainder of 10 divided by 3",
            Some("math"),
            "natural: remainder",
            ExpectedOutcome::Ok("math"),
        ),
    ]
}

#[test]
fn imported_super_calculator_math_cases() {
    block_on(run_cases("math", cases()));
}
