#[path = "support/mod.rs"]
mod support;

use support::{Case, ExpectedOutcome, block_on, case, run_cases};

pub fn cases() -> Vec<Case> {
    vec![
        // TIME ZONES - City names
        case(
            "time in tokyo",
            Some("time"),
            "time in tokyo",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in new york",
            Some("time"),
            "time in new york",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in madison",
            Some("time"),
            "time in madison",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in london",
            Some("time"),
            "time in london",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in paris",
            Some("time"),
            "time in paris",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in berlin",
            Some("time"),
            "time in berlin",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in sydney",
            Some("time"),
            "time in sydney",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in mumbai",
            Some("time"),
            "time in mumbai",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in beijing",
            Some("time"),
            "time in beijing",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in dubai",
            Some("time"),
            "time in dubai",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in singapore",
            Some("time"),
            "time in singapore",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in hong kong",
            Some("time"),
            "time in hong kong",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in los angeles",
            Some("time"),
            "time in los angeles",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in chicago",
            Some("time"),
            "time in chicago",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in denver",
            Some("time"),
            "time in denver",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in toronto",
            Some("time"),
            "time in toronto",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in moscow",
            Some("time"),
            "time in moscow",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in seoul",
            Some("time"),
            "time in seoul",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in bangkok",
            Some("time"),
            "time in bangkok",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in cairo",
            Some("time"),
            "time in cairo",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in istanbul",
            Some("time"),
            "time in istanbul",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in san francisco",
            Some("time"),
            "time in san francisco",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in seattle",
            Some("time"),
            "time in seattle",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in boston",
            Some("time"),
            "time in boston",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in miami",
            Some("time"),
            "time in miami",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in dallas",
            Some("time"),
            "time in dallas",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in phoenix",
            Some("time"),
            "time in phoenix",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in honolulu",
            Some("time"),
            "time in honolulu",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in anchorage",
            Some("time"),
            "time in anchorage",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in amsterdam",
            Some("time"),
            "time in amsterdam",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in rome",
            Some("time"),
            "time in rome",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in madrid",
            Some("time"),
            "time in madrid",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in lisbon",
            Some("time"),
            "time in lisbon",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in zurich",
            Some("time"),
            "time in zurich",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in vienna",
            Some("time"),
            "time in vienna",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in stockholm",
            Some("time"),
            "time in stockholm",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in oslo",
            Some("time"),
            "time in oslo",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in helsinki",
            Some("time"),
            "time in helsinki",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in warsaw",
            Some("time"),
            "time in warsaw",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in prague",
            Some("time"),
            "time in prague",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in jakarta",
            Some("time"),
            "time in jakarta",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in manila",
            Some("time"),
            "time in manila",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in kuala lumpur",
            Some("time"),
            "time in kuala lumpur",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in delhi",
            Some("time"),
            "time in delhi",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in kolkata",
            Some("time"),
            "time in kolkata",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in bangalore",
            Some("time"),
            "time in bangalore",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in chennai",
            Some("time"),
            "time in chennai",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in hyderabad",
            Some("time"),
            "time in hyderabad",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in auckland",
            Some("time"),
            "time in auckland",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in melbourne",
            Some("time"),
            "time in melbourne",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in sao paulo",
            Some("time"),
            "time in sao paulo",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in buenos aires",
            Some("time"),
            "time in buenos aires",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in lagos",
            Some("time"),
            "time in lagos",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in nairobi",
            Some("time"),
            "time in nairobi",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in johannesburg",
            Some("time"),
            "time in johannesburg",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in riyadh",
            Some("time"),
            "time in riyadh",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in tehran",
            Some("time"),
            "time in tehran",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in kathmandu",
            Some("time"),
            "time in kathmandu",
            ExpectedOutcome::Ok("time"),
        ),
        // TIME ZONES - Country names
        case(
            "time in india",
            Some("time"),
            "time in india",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in germany",
            Some("time"),
            "time in germany",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in japan",
            Some("time"),
            "time in japan",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in australia",
            Some("time"),
            "time in australia",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in uk",
            Some("time"),
            "time in uk",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in usa",
            Some("time"),
            "time in usa",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in china",
            Some("time"),
            "time in china",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in brazil",
            Some("time"),
            "time in brazil",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in canada",
            Some("time"),
            "time in canada",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in france",
            Some("time"),
            "time in france",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in italy",
            Some("time"),
            "time in italy",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in spain",
            Some("time"),
            "time in spain",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in russia",
            Some("time"),
            "time in russia",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in south korea",
            Some("time"),
            "time in south korea",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in mexico",
            Some("time"),
            "time in mexico",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in indonesia",
            Some("time"),
            "time in indonesia",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in thailand",
            Some("time"),
            "time in thailand",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in malaysia",
            Some("time"),
            "time in malaysia",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in philippines",
            Some("time"),
            "time in philippines",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in new zealand",
            Some("time"),
            "time in new zealand",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in south africa",
            Some("time"),
            "time in south africa",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in egypt",
            Some("time"),
            "time in egypt",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in turkey",
            Some("time"),
            "time in turkey",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in saudi arabia",
            Some("time"),
            "time in saudi arabia",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in nepal",
            Some("time"),
            "time in nepal",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in pakistan",
            Some("time"),
            "time in pakistan",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in bangladesh",
            Some("time"),
            "time in bangladesh",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in sri lanka",
            Some("time"),
            "time in sri lanka",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in nigeria",
            Some("time"),
            "time in nigeria",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in kenya",
            Some("time"),
            "time in kenya",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in argentina",
            Some("time"),
            "time in argentina",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in colombia",
            Some("time"),
            "time in colombia",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in peru",
            Some("time"),
            "time in peru",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in chile",
            Some("time"),
            "time in chile",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in ireland",
            Some("time"),
            "time in ireland",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in portugal",
            Some("time"),
            "time in portugal",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in switzerland",
            Some("time"),
            "time in switzerland",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in sweden",
            Some("time"),
            "time in sweden",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in norway",
            Some("time"),
            "time in norway",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in finland",
            Some("time"),
            "time in finland",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in poland",
            Some("time"),
            "time in poland",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in ukraine",
            Some("time"),
            "time in ukraine",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in greece",
            Some("time"),
            "time in greece",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in vietnam",
            Some("time"),
            "time in vietnam",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in taiwan",
            Some("time"),
            "time in taiwan",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in uae",
            Some("time"),
            "time in uae",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in iran",
            Some("time"),
            "time in iran",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in iraq",
            Some("time"),
            "time in iraq",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in israel",
            Some("time"),
            "time in israel",
            ExpectedOutcome::Ok("time"),
        ),
        // TIME ZONES - Abbreviations
        case(
            "time in pst",
            Some("time"),
            "time in PST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in est",
            Some("time"),
            "time in EST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in cst",
            Some("time"),
            "time in CST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in mst",
            Some("time"),
            "time in MST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in ist",
            Some("time"),
            "time in IST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in gmt",
            Some("time"),
            "time in GMT",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in utc",
            Some("time"),
            "time in UTC",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in jst",
            Some("time"),
            "time in JST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in kst",
            Some("time"),
            "time in KST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in cet",
            Some("time"),
            "time in CET",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in eet",
            Some("time"),
            "time in EET",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in aest",
            Some("time"),
            "time in AEST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in hkt",
            Some("time"),
            "time in HKT",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in sgt",
            Some("time"),
            "time in SGT",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in bst",
            Some("time"),
            "time in BST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in pdt",
            Some("time"),
            "time in PDT",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in edt",
            Some("time"),
            "time in EDT",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in cdt",
            Some("time"),
            "time in CDT",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time in mdt",
            Some("time"),
            "time in MDT",
            ExpectedOutcome::Ok("time"),
        ),
        // TIME ZONES - Conversions
        case(
            "india to us time",
            Some("time"),
            "india to us time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "utc to ist",
            Some("time"),
            "utc to ist",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "pst to est",
            Some("time"),
            "pst to est",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "ist to pst",
            Some("time"),
            "ist to pst",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "ist to madison time",
            Some("time"),
            "ist to madison time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "12:30 ist to madison",
            Some("time"),
            "specific time IST to madison",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "3:00 pm est to pst",
            Some("time"),
            "specific time EST to PST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "9:00 am pst to ist",
            Some("time"),
            "morning PST to IST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "midnight utc to ist",
            Some("time"),
            "midnight UTC to IST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "noon est to pst",
            Some("time"),
            "noon EST to PST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "tokyo to new york time",
            Some("time"),
            "city to city time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "london to tokyo time",
            Some("time"),
            "london to tokyo",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "est to jst",
            Some("time"),
            "east coast to japan",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "gmt to ist",
            Some("time"),
            "gmt to india",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "cet to pst",
            Some("time"),
            "central europe to pacific",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "india to japan time",
            Some("time"),
            "country to country time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "us to india time",
            Some("time"),
            "us to india",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "uk to india time",
            Some("time"),
            "uk to india",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "australia to india time",
            Some("time"),
            "australia to india",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "5:30 pm ist to est",
            Some("time"),
            "5:30 pm IST to EST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "10:00 jst to cet",
            Some("time"),
            "10am Japan to Central Europe",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "14:00 utc to pst",
            Some("time"),
            "2pm UTC to PST",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "23:59 ist to utc",
            Some("time"),
            "late night IST to UTC",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "00:00 utc to ist",
            Some("time"),
            "midnight UTC to IST",
            ExpectedOutcome::Ok("time"),
        ),
        // TIME ZONES - Natural Language Variations
        case(
            "what time is it in tokyo",
            Some("time"),
            "natural: what time in tokyo",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "current time in london",
            Some("time"),
            "natural: current time in london",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "whats the time in paris",
            Some("time"),
            "natural: whats the time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "what is the time in berlin",
            Some("time"),
            "natural: what is the time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "time now in singapore",
            Some("time"),
            "natural: time now in",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "now in tokyo",
            Some("time"),
            "natural: now in city",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "tokyo time",
            Some("time"),
            "natural: city time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "new york time",
            Some("time"),
            "natural: new york time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "india time",
            Some("time"),
            "natural: country time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "london time",
            Some("time"),
            "natural: london time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "ist time",
            Some("time"),
            "natural: abbrev time",
            ExpectedOutcome::Ok("time"),
        ),
        case(
            "pst time",
            Some("time"),
            "natural: pst time",
            ExpectedOutcome::Ok("time"),
        ),
    ]
}

#[test]
fn imported_super_calculator_time_cases() {
    block_on(run_cases("time", cases()));
}
